spring.datasource.url=jdbc:postgresql://localhost:5432/ingresosygastos
spring.datasource.username=postgres
spring.datasource.password=jeff0831
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
#Muestra en consola las consutas SQL que hibernarte haga
spring.jpa.show-sql=true


logging.level.root=INFO