spring.datasource.url=jdbc:postgresql://localhost:5432/nombre_de_tu_bd
spring.datasource.username=postgres
spring.datasource.password=jeff0831@100
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=create

#Muestra en consola las consutas SQL que hibernarte haga
spring.jpa.show-sql=true